version: '3'
tasks:
  run:
    cmds:
      - echo "Compiling postago..."
      - go build -o ./bin/postago ./src/main.go
      - echo "Running postago..."
      - ./bin/postago
  build:
    cmds:
      - echo "Building postago..."
      - go build -o ./bin/postago ./src/main.go
  